import Head from "next/head";
import styled from "styled-components";
import Pokemon from "@/components/Pokemon";

const Container = styled.div`
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  padding: 1rem 2rem;

  @media (max-width: 768px) {
    padding: 0;
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokémon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./images/pikachu.ico" type="image/x-icon" />
      </Head>
      <Container>
        <Pokemon />
      </Container>
    </>
  );
}
